### ISSUE TITLE
scarmapper does not work although all modules are installed

### ISSUE THREAD

**Issue by RobinVanSchendel** [Gaorav-Gupta-Lab/ScarMapper#43] opened 2021-06-16 14:52 UTC
Traceback (most recent call last):
  File "scarmapper.py", line 27, in <module>
    folder_content = os.listdir("{0}{1}scarmapper{1}".format(os.path.dirname(__file__), os.sep))
FileNotFoundError: [Errno 2] No such file or directory: '/scarmapper/'

while I am in the directory where ScarMapper is:

/exports/humgen/rvanschendel/ScarMapper

with contents:

 FASTQ_Preprocess.py   Indices   LICENSE.md  'No setup.py'   Pear   README.md   Valkyries   docs   scarmapper   scarmapper.py

**Comment by pkMyt1** [comment] 2021-06-16 17:46
Sorry about this.  I thought I had this requirement working.  The first time you run ScarMapper it needs to cythonize the sliding window file.  I can walk you through the manual method. 

cd into the scarmapper/ directory and execute python3 setup.py build_ext --inplace to build the SlidingWindow.c and SlidingWindow.cpython-37m-x86_64-linux-gnu.so files.  

I am going to upload a requirements.txt file in a few seconds here as well.

**Comment by RobinVanSchendel** [comment] 2021-06-17 07:22
That results in:

/exports/humgen/rvanschendel/ScarMapper/scarmapper$ python3.6 setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    ext_modules=cythonize(slidingwindow_file, annotate=True)
  File "/home/rvanschendel/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 972, in cythonize
    aliases=aliases)
  File "/home/rvanschendel/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/home/rvanschendel/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
    raise ValueError(error_msg)
ValueError: '/SlidingWindow.pyx' doesn't match any files

**Comment by pkMyt1** [comment] 2021-06-17 11:38
Can you tell me which OS you are running this on?  I would like to try and replicate this error here.  The path being returned by os.path.dirname is not what is expected.  This is causing the error in both locations.  I think (hope) `'{0}{1}SlidingWindow.pyx'.format(os.path.dirname(__file__), os.sep)`  is returning /exports/humgen/rvanschendel/ScarMapper/scarmapper//SlidingWindow.pyx on your machine.  If you are willing to try another test, replace the setup.py in /scarmapper with the attached file, rename it to setup.py and run the build again.
[setup.py.txt](https://github.com/Gaorav-Gupta-Lab/ScarMapper/files/6669787/setup.py.txt)

**Comment by RobinVanSchendel** [comment] 2021-06-17 14:49
I am running CentOs 8. the attached file setup.py.txt indeed works runs now without issues (and compiles a few files). I am still unable to start scarmapper though, but I hope that you can also fix that using this information.

**Comment by pkMyt1** [comment] 2021-06-17 14:56
Thank you.  Very helpful.  I had used CentOS 7 but have not tried it on 8.  I will upload a fix to GitHub within an hour.

**Comment by pkMyt1** [comment] 2021-06-17 16:02
Pull a new set of files and try it now.

**Comment by RobinVanSchendel** [comment] 2021-06-18 06:25
I think the line in setup.py:

slidingwindow_file = '{}SlidingWindow.pyx'.format(pathlib.Path(__file__).parent.absolute(), os.sep)

should be:

slidingwindow_file = '{}{}SlidingWindow.pyx'.format(pathlib.Path(__file__).parent.absolute(), os.sep)

Also you scarmapper.py has a hardcoded "python3" statement. On my system however, there are multiple versions of python 3 installed. It would be better if I start the program with: python3.6 scarmapper.py that you retrieve "python3.6" from the program invocation and use that in line 54. 

This together works:

usage: scarmapper.py [-h] --options_file OPTIONS_FILE
scarmapper.py: error: the following arguments are required: --options_file

**Comment by pkMyt1** [comment] 2021-06-18 20:18
I installed a virtual CentOS8 here and chased this down.  Looks like it is the Python build that comes with CentOS8 handles the path lookups a bit differently.  I have changed the path lookups to work with it and my other installations here.  It has been confirmed on Python 3.6 and 3.7 now.  I am getting a timeout warning on my CentOS 8 that has to do with gnome but ScarMapper is completing successfully.  When I Google this error it comes back as a gnome scrollbar overlay issue but turning it off doesn't appear to change it for me.  I am uploading the corrected files now.  Thanks for bearing with me on this.

**Comment by pkMyt1** [comment] 2021-06-28 11:13
Is this working for you now?

**Comment by RobinVanSchendel** [comment] 2021-06-28 12:49
Still does not work. The issue is that the file SlidingWindow.cpython-36m-x86_64-linux-gnu.so is put into the subdirectory:

./scarmapper/scarmapper/SlidingWindow.cpython-36m-x86_64-linux-gnu.so

Not the double scarmapper/scarmapper. When I do:

mv scarmapper/scarmapper/SlidingWindow.cpython-36m-x86_64-linux-gnu.so scarmapper

it runs.

**Comment by pkMyt1** [comment] 2021-06-28 14:13
So to be clear, it is working now that you moved the .so file however when it is first run it puts that file in the wrong location.  I will need to talk with some of the programmers around here and try and solve this.  In the mean time, if you would like a FASTQ set that is better than what was published,  email me directly, dennis at email dot unc dot edu.  I can get you the FASTQ files, targets file, options file, and sample manifest of one of the recent ones that works well.

**Comment by pkMyt1** [comment] 2021-11-16 12:33
Closing this for now.  @RobinVanSchendel has it working and we have been unable to reproduce the problem locally.  If it still occurs we can revisit this.

**Closed** 2021-11-16 12:33 UTC
